/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fyp.core.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroTripUpdateEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4000901943687193056L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTripUpdateEvent\",\"namespace\":\"com.fyp.avro\",\"fields\":[{\"name\":\"tripId\",\"type\":\"string\"},{\"name\":\"startTime\",\"type\":\"string\"},{\"name\":\"startDate\",\"type\":\"string\"},{\"name\":\"scheduleRelationship\",\"type\":\"string\"},{\"name\":\"routeId\",\"type\":\"string\"},{\"name\":\"tripUpdateTimestamp\",\"type\":\"string\"},{\"name\":\"stopTimeUpdates\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroStopTimeUpdate\",\"fields\":[{\"name\":\"stopSequence\",\"type\":\"string\"},{\"name\":\"aDelay\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"dDelay\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"stopId\",\"type\":\"string\"},{\"name\":\"stopTimeUpdateScheduleRelationship\",\"type\":[\"null\",\"string\"],\"default\":null}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroTripUpdateEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroTripUpdateEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroTripUpdateEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroTripUpdateEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroTripUpdateEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroTripUpdateEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroTripUpdateEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroTripUpdateEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroTripUpdateEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence tripId;
  private java.lang.CharSequence startTime;
  private java.lang.CharSequence startDate;
  private java.lang.CharSequence scheduleRelationship;
  private java.lang.CharSequence routeId;
  private java.lang.CharSequence tripUpdateTimestamp;
  private java.util.List<AvroStopTimeUpdate> stopTimeUpdates;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroTripUpdateEvent() {}

  /**
   * All-args constructor.
   * @param tripId The new value for tripId
   * @param startTime The new value for startTime
   * @param startDate The new value for startDate
   * @param scheduleRelationship The new value for scheduleRelationship
   * @param routeId The new value for routeId
   * @param tripUpdateTimestamp The new value for tripUpdateTimestamp
   * @param stopTimeUpdates The new value for stopTimeUpdates
   */
  public AvroTripUpdateEvent(java.lang.CharSequence tripId, java.lang.CharSequence startTime, java.lang.CharSequence startDate, java.lang.CharSequence scheduleRelationship, java.lang.CharSequence routeId, java.lang.CharSequence tripUpdateTimestamp, java.util.List<AvroStopTimeUpdate> stopTimeUpdates) {
    this.tripId = tripId;
    this.startTime = startTime;
    this.startDate = startDate;
    this.scheduleRelationship = scheduleRelationship;
    this.routeId = routeId;
    this.tripUpdateTimestamp = tripUpdateTimestamp;
    this.stopTimeUpdates = stopTimeUpdates;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tripId;
    case 1: return startTime;
    case 2: return startDate;
    case 3: return scheduleRelationship;
    case 4: return routeId;
    case 5: return tripUpdateTimestamp;
    case 6: return stopTimeUpdates;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tripId = (java.lang.CharSequence)value$; break;
    case 1: startTime = (java.lang.CharSequence)value$; break;
    case 2: startDate = (java.lang.CharSequence)value$; break;
    case 3: scheduleRelationship = (java.lang.CharSequence)value$; break;
    case 4: routeId = (java.lang.CharSequence)value$; break;
    case 5: tripUpdateTimestamp = (java.lang.CharSequence)value$; break;
    case 6: stopTimeUpdates = (java.util.List<AvroStopTimeUpdate>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tripId' field.
   * @return The value of the 'tripId' field.
   */
  public java.lang.CharSequence getTripId() {
    return tripId;
  }


  /**
   * Sets the value of the 'tripId' field.
   * @param value the value to set.
   */
  public void setTripId(java.lang.CharSequence value) {
    this.tripId = value;
  }

  /**
   * Gets the value of the 'startTime' field.
   * @return The value of the 'startTime' field.
   */
  public java.lang.CharSequence getStartTime() {
    return startTime;
  }


  /**
   * Sets the value of the 'startTime' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.CharSequence value) {
    this.startTime = value;
  }

  /**
   * Gets the value of the 'startDate' field.
   * @return The value of the 'startDate' field.
   */
  public java.lang.CharSequence getStartDate() {
    return startDate;
  }


  /**
   * Sets the value of the 'startDate' field.
   * @param value the value to set.
   */
  public void setStartDate(java.lang.CharSequence value) {
    this.startDate = value;
  }

  /**
   * Gets the value of the 'scheduleRelationship' field.
   * @return The value of the 'scheduleRelationship' field.
   */
  public java.lang.CharSequence getScheduleRelationship() {
    return scheduleRelationship;
  }


  /**
   * Sets the value of the 'scheduleRelationship' field.
   * @param value the value to set.
   */
  public void setScheduleRelationship(java.lang.CharSequence value) {
    this.scheduleRelationship = value;
  }

  /**
   * Gets the value of the 'routeId' field.
   * @return The value of the 'routeId' field.
   */
  public java.lang.CharSequence getRouteId() {
    return routeId;
  }


  /**
   * Sets the value of the 'routeId' field.
   * @param value the value to set.
   */
  public void setRouteId(java.lang.CharSequence value) {
    this.routeId = value;
  }

  /**
   * Gets the value of the 'tripUpdateTimestamp' field.
   * @return The value of the 'tripUpdateTimestamp' field.
   */
  public java.lang.CharSequence getTripUpdateTimestamp() {
    return tripUpdateTimestamp;
  }


  /**
   * Sets the value of the 'tripUpdateTimestamp' field.
   * @param value the value to set.
   */
  public void setTripUpdateTimestamp(java.lang.CharSequence value) {
    this.tripUpdateTimestamp = value;
  }

  /**
   * Gets the value of the 'stopTimeUpdates' field.
   * @return The value of the 'stopTimeUpdates' field.
   */
  public java.util.List<AvroStopTimeUpdate> getStopTimeUpdates() {
    return stopTimeUpdates;
  }


  /**
   * Sets the value of the 'stopTimeUpdates' field.
   * @param value the value to set.
   */
  public void setStopTimeUpdates(java.util.List<AvroStopTimeUpdate> value) {
    this.stopTimeUpdates = value;
  }

  /**
   * Creates a new AvroTripUpdateEvent RecordBuilder.
   * @return A new AvroTripUpdateEvent RecordBuilder
   */
  public static AvroTripUpdateEvent.Builder newBuilder() {
    return new AvroTripUpdateEvent.Builder();
  }

  /**
   * Creates a new AvroTripUpdateEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroTripUpdateEvent RecordBuilder
   */
  public static AvroTripUpdateEvent.Builder newBuilder(AvroTripUpdateEvent.Builder other) {
    if (other == null) {
      return new AvroTripUpdateEvent.Builder();
    } else {
      return new AvroTripUpdateEvent.Builder(other);
    }
  }

  /**
   * Creates a new AvroTripUpdateEvent RecordBuilder by copying an existing AvroTripUpdateEvent instance.
   * @param other The existing instance to copy.
   * @return A new AvroTripUpdateEvent RecordBuilder
   */
  public static AvroTripUpdateEvent.Builder newBuilder(AvroTripUpdateEvent other) {
    if (other == null) {
      return new AvroTripUpdateEvent.Builder();
    } else {
      return new AvroTripUpdateEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroTripUpdateEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTripUpdateEvent>
    implements org.apache.avro.data.RecordBuilder<AvroTripUpdateEvent> {

    private java.lang.CharSequence tripId;
    private java.lang.CharSequence startTime;
    private java.lang.CharSequence startDate;
    private java.lang.CharSequence scheduleRelationship;
    private java.lang.CharSequence routeId;
    private java.lang.CharSequence tripUpdateTimestamp;
    private java.util.List<AvroStopTimeUpdate> stopTimeUpdates;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AvroTripUpdateEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tripId)) {
        this.tripId = data().deepCopy(fields()[0].schema(), other.tripId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.startTime)) {
        this.startTime = data().deepCopy(fields()[1].schema(), other.startTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.startDate)) {
        this.startDate = data().deepCopy(fields()[2].schema(), other.startDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.scheduleRelationship)) {
        this.scheduleRelationship = data().deepCopy(fields()[3].schema(), other.scheduleRelationship);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.routeId)) {
        this.routeId = data().deepCopy(fields()[4].schema(), other.routeId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.tripUpdateTimestamp)) {
        this.tripUpdateTimestamp = data().deepCopy(fields()[5].schema(), other.tripUpdateTimestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.stopTimeUpdates)) {
        this.stopTimeUpdates = data().deepCopy(fields()[6].schema(), other.stopTimeUpdates);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroTripUpdateEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroTripUpdateEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.tripId)) {
        this.tripId = data().deepCopy(fields()[0].schema(), other.tripId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startTime)) {
        this.startTime = data().deepCopy(fields()[1].schema(), other.startTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.startDate)) {
        this.startDate = data().deepCopy(fields()[2].schema(), other.startDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.scheduleRelationship)) {
        this.scheduleRelationship = data().deepCopy(fields()[3].schema(), other.scheduleRelationship);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.routeId)) {
        this.routeId = data().deepCopy(fields()[4].schema(), other.routeId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tripUpdateTimestamp)) {
        this.tripUpdateTimestamp = data().deepCopy(fields()[5].schema(), other.tripUpdateTimestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.stopTimeUpdates)) {
        this.stopTimeUpdates = data().deepCopy(fields()[6].schema(), other.stopTimeUpdates);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'tripId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTripId() {
      return tripId;
    }


    /**
      * Sets the value of the 'tripId' field.
      * @param value The value of 'tripId'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setTripId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tripId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tripId' field has been set.
      * @return True if the 'tripId' field has been set, false otherwise.
      */
    public boolean hasTripId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tripId' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearTripId() {
      tripId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'startTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartTime() {
      return startTime;
    }


    /**
      * Sets the value of the 'startTime' field.
      * @param value The value of 'startTime'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setStartTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.startTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'startTime' field has been set.
      * @return True if the 'startTime' field has been set, false otherwise.
      */
    public boolean hasStartTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'startTime' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearStartTime() {
      startTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'startDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartDate() {
      return startDate;
    }


    /**
      * Sets the value of the 'startDate' field.
      * @param value The value of 'startDate'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setStartDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.startDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'startDate' field has been set.
      * @return True if the 'startDate' field has been set, false otherwise.
      */
    public boolean hasStartDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'startDate' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearStartDate() {
      startDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'scheduleRelationship' field.
      * @return The value.
      */
    public java.lang.CharSequence getScheduleRelationship() {
      return scheduleRelationship;
    }


    /**
      * Sets the value of the 'scheduleRelationship' field.
      * @param value The value of 'scheduleRelationship'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setScheduleRelationship(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.scheduleRelationship = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'scheduleRelationship' field has been set.
      * @return True if the 'scheduleRelationship' field has been set, false otherwise.
      */
    public boolean hasScheduleRelationship() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'scheduleRelationship' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearScheduleRelationship() {
      scheduleRelationship = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'routeId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRouteId() {
      return routeId;
    }


    /**
      * Sets the value of the 'routeId' field.
      * @param value The value of 'routeId'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setRouteId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.routeId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'routeId' field has been set.
      * @return True if the 'routeId' field has been set, false otherwise.
      */
    public boolean hasRouteId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'routeId' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearRouteId() {
      routeId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'tripUpdateTimestamp' field.
      * @return The value.
      */
    public java.lang.CharSequence getTripUpdateTimestamp() {
      return tripUpdateTimestamp;
    }


    /**
      * Sets the value of the 'tripUpdateTimestamp' field.
      * @param value The value of 'tripUpdateTimestamp'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setTripUpdateTimestamp(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.tripUpdateTimestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'tripUpdateTimestamp' field has been set.
      * @return True if the 'tripUpdateTimestamp' field has been set, false otherwise.
      */
    public boolean hasTripUpdateTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'tripUpdateTimestamp' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearTripUpdateTimestamp() {
      tripUpdateTimestamp = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'stopTimeUpdates' field.
      * @return The value.
      */
    public java.util.List<AvroStopTimeUpdate> getStopTimeUpdates() {
      return stopTimeUpdates;
    }


    /**
      * Sets the value of the 'stopTimeUpdates' field.
      * @param value The value of 'stopTimeUpdates'.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder setStopTimeUpdates(java.util.List<AvroStopTimeUpdate> value) {
      validate(fields()[6], value);
      this.stopTimeUpdates = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'stopTimeUpdates' field has been set.
      * @return True if the 'stopTimeUpdates' field has been set, false otherwise.
      */
    public boolean hasStopTimeUpdates() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'stopTimeUpdates' field.
      * @return This builder.
      */
    public AvroTripUpdateEvent.Builder clearStopTimeUpdates() {
      stopTimeUpdates = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroTripUpdateEvent build() {
      try {
        AvroTripUpdateEvent record = new AvroTripUpdateEvent();
        record.tripId = fieldSetFlags()[0] ? this.tripId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.startTime = fieldSetFlags()[1] ? this.startTime : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.startDate = fieldSetFlags()[2] ? this.startDate : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.scheduleRelationship = fieldSetFlags()[3] ? this.scheduleRelationship : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.routeId = fieldSetFlags()[4] ? this.routeId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.tripUpdateTimestamp = fieldSetFlags()[5] ? this.tripUpdateTimestamp : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.stopTimeUpdates = fieldSetFlags()[6] ? this.stopTimeUpdates : (java.util.List<AvroStopTimeUpdate>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroTripUpdateEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroTripUpdateEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroTripUpdateEvent>
    READER$ = (org.apache.avro.io.DatumReader<AvroTripUpdateEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tripId);

    out.writeString(this.startTime);

    out.writeString(this.startDate);

    out.writeString(this.scheduleRelationship);

    out.writeString(this.routeId);

    out.writeString(this.tripUpdateTimestamp);

    long size0 = this.stopTimeUpdates.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (AvroStopTimeUpdate e0: this.stopTimeUpdates) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);

      this.startTime = in.readString(this.startTime instanceof Utf8 ? (Utf8)this.startTime : null);

      this.startDate = in.readString(this.startDate instanceof Utf8 ? (Utf8)this.startDate : null);

      this.scheduleRelationship = in.readString(this.scheduleRelationship instanceof Utf8 ? (Utf8)this.scheduleRelationship : null);

      this.routeId = in.readString(this.routeId instanceof Utf8 ? (Utf8)this.routeId : null);

      this.tripUpdateTimestamp = in.readString(this.tripUpdateTimestamp instanceof Utf8 ? (Utf8)this.tripUpdateTimestamp : null);

      long size0 = in.readArrayStart();
      java.util.List<AvroStopTimeUpdate> a0 = this.stopTimeUpdates;
      if (a0 == null) {
        a0 = new SpecificData.Array<AvroStopTimeUpdate>((int)size0, SCHEMA$.getField("stopTimeUpdates").schema());
        this.stopTimeUpdates = a0;
      } else a0.clear();
      SpecificData.Array<AvroStopTimeUpdate> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<AvroStopTimeUpdate>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          AvroStopTimeUpdate e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new AvroStopTimeUpdate();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);
          break;

        case 1:
          this.startTime = in.readString(this.startTime instanceof Utf8 ? (Utf8)this.startTime : null);
          break;

        case 2:
          this.startDate = in.readString(this.startDate instanceof Utf8 ? (Utf8)this.startDate : null);
          break;

        case 3:
          this.scheduleRelationship = in.readString(this.scheduleRelationship instanceof Utf8 ? (Utf8)this.scheduleRelationship : null);
          break;

        case 4:
          this.routeId = in.readString(this.routeId instanceof Utf8 ? (Utf8)this.routeId : null);
          break;

        case 5:
          this.tripUpdateTimestamp = in.readString(this.tripUpdateTimestamp instanceof Utf8 ? (Utf8)this.tripUpdateTimestamp : null);
          break;

        case 6:
          long size0 = in.readArrayStart();
          java.util.List<AvroStopTimeUpdate> a0 = this.stopTimeUpdates;
          if (a0 == null) {
            a0 = new SpecificData.Array<AvroStopTimeUpdate>((int)size0, SCHEMA$.getField("stopTimeUpdates").schema());
            this.stopTimeUpdates = a0;
          } else a0.clear();
          SpecificData.Array<AvroStopTimeUpdate> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<AvroStopTimeUpdate>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              AvroStopTimeUpdate e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new AvroStopTimeUpdate();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










