services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 5s
      retries: 5

  broker:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker
    container_name: broker
    #    use broker:9092 inside docker, localhost:9092 for things accessing outside of container on the machine
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
#    this 29092 is an arbitrary port for host machine
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: W1lburgra!
      MYSQL_DATABASE: flink_test
      MYSQL_USER: flink
      MYSQL_PASSWORD: flink

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # Needed for metadata
  druid-postgres:
    image: postgres:latest
    container_name: druid-postgres
    environment:
      POSTGRES_USER: druid
      POSTGRES_PASSWORD: druid
      POSTGRES_DB: druid
    ports:
      - "5432:5432"

  druid-router:
    image: apache/druid:28.0.0
    container_name: druid-router
    command: router
    depends_on:
      - druid-coordinator
    ports:
      - "8888:8888"
    environment:
      - DRUID_XMS=2g
      - DRUID_XMX=2g
      - DRUID_MAXDIRECTMEMORYSIZE=6g
      - JAVA_OPTS=-server -XX:+UseG1GC

  druid-coordinator:
    image: apache/druid:28.0.0
    container_name: druid-coordinator
    command: coordinator
    depends_on:
      - druid-postgres
    environment:
      DRUID_METADATA_STORAGE_TYPE: postgresql
      DRUID_METADATA_STORAGE_HOST: postgres
      DRUID_METADATA_STORAGE_DB: druid
      DRUID_METADATA_STORAGE_USER: druid
      DRUID_METADATA_STORAGE_PASSWORD: druid
      DRUID_XMS: 2g
      DRUID_XMX: 2g
      DRUID_MAXDIRECTMEMORYSIZE: 6g
      JAVA_OPTS: -server -XX:+UseG1GC

  druid-overlord:
    image: apache/druid:28.0.0
    container_name: druid-overlord
    command: overlord
    depends_on:
      - druid-postgres
    ports:
      - "8091:8091"
    environment:
      - DRUID_XMS=2g
      - DRUID_XMX=2g
      - DRUID_MAXDIRECTMEMORYSIZE=6g
      - JAVA_OPTS=-server -XX:+UseG1GC

  druid-broker:
    image: apache/druid:28.0.0
    container_name: druid-broker
    command: broker
    environment:
      - DRUID_XMS=2g
      - DRUID_XMX=2g
      - DRUID_MAXDIRECTMEMORYSIZE=6g
      - JAVA_OPTS=-server -XX:+UseG1GC

  druid-historical:
    image: apache/druid:28.0.0
    container_name: druid-historical
    command: historical
    volumes:
      - ./druid/segments:/opt/druid/segments # For configuring deep storage, historical reads
    environment:
      - DRUID_XMS=2g
      - DRUID_XMX=2g
      - DRUID_MAXDIRECTMEMORYSIZE=6g
      - JAVA_OPTS=-server -XX:+UseG1GC
      - druid.storage.type=local
      - druid.storage.storageDirectory=/opt/druid/segments

  druid-middlemanager:
    image: apache/druid:28.0.0
    container_name: druid-middlemanager
    command: middleManager
    volumes:
      - ./druid/segments:/opt/druid/segments # For configuring deep storage, middlemanager writes
    environment:
      - DRUID_XMS=2g
      - DRUID_XMX=2g
      - DRUID_MAXDIRECTMEMORYSIZE=6g
      - JAVA_OPTS=-server -XX:+UseG1GC
      - druid.storage.type=local
      - druid.storage.storageDirectory=/opt/druid/segments
