/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class VehicleEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6268151056666006496L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VehicleEvent\",\"fields\":[{\"name\":\"tripId\",\"type\":\"string\"},{\"name\":\"startTime\",\"type\":\"string\"},{\"name\":\"startData\",\"type\":\"string\"},{\"name\":\"scheduleRelationship\",\"type\":\"string\"},{\"name\":\"routeId\",\"type\":\"string\"},{\"name\":\"vehicleTimestamp\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VehicleEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VehicleEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VehicleEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VehicleEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VehicleEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VehicleEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VehicleEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VehicleEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VehicleEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence tripId;
  private java.lang.CharSequence startTime;
  private java.lang.CharSequence startData;
  private java.lang.CharSequence scheduleRelationship;
  private java.lang.CharSequence routeId;
  private java.lang.CharSequence vehicleTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VehicleEvent() {}

  /**
   * All-args constructor.
   * @param tripId The new value for tripId
   * @param startTime The new value for startTime
   * @param startData The new value for startData
   * @param scheduleRelationship The new value for scheduleRelationship
   * @param routeId The new value for routeId
   * @param vehicleTimestamp The new value for vehicleTimestamp
   */
  public VehicleEvent(java.lang.CharSequence tripId, java.lang.CharSequence startTime, java.lang.CharSequence startData, java.lang.CharSequence scheduleRelationship, java.lang.CharSequence routeId, java.lang.CharSequence vehicleTimestamp) {
    this.tripId = tripId;
    this.startTime = startTime;
    this.startData = startData;
    this.scheduleRelationship = scheduleRelationship;
    this.routeId = routeId;
    this.vehicleTimestamp = vehicleTimestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tripId;
    case 1: return startTime;
    case 2: return startData;
    case 3: return scheduleRelationship;
    case 4: return routeId;
    case 5: return vehicleTimestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tripId = (java.lang.CharSequence)value$; break;
    case 1: startTime = (java.lang.CharSequence)value$; break;
    case 2: startData = (java.lang.CharSequence)value$; break;
    case 3: scheduleRelationship = (java.lang.CharSequence)value$; break;
    case 4: routeId = (java.lang.CharSequence)value$; break;
    case 5: vehicleTimestamp = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tripId' field.
   * @return The value of the 'tripId' field.
   */
  public java.lang.CharSequence getTripId() {
    return tripId;
  }


  /**
   * Sets the value of the 'tripId' field.
   * @param value the value to set.
   */
  public void setTripId(java.lang.CharSequence value) {
    this.tripId = value;
  }

  /**
   * Gets the value of the 'startTime' field.
   * @return The value of the 'startTime' field.
   */
  public java.lang.CharSequence getStartTime() {
    return startTime;
  }


  /**
   * Sets the value of the 'startTime' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.CharSequence value) {
    this.startTime = value;
  }

  /**
   * Gets the value of the 'startData' field.
   * @return The value of the 'startData' field.
   */
  public java.lang.CharSequence getStartData() {
    return startData;
  }


  /**
   * Sets the value of the 'startData' field.
   * @param value the value to set.
   */
  public void setStartData(java.lang.CharSequence value) {
    this.startData = value;
  }

  /**
   * Gets the value of the 'scheduleRelationship' field.
   * @return The value of the 'scheduleRelationship' field.
   */
  public java.lang.CharSequence getScheduleRelationship() {
    return scheduleRelationship;
  }


  /**
   * Sets the value of the 'scheduleRelationship' field.
   * @param value the value to set.
   */
  public void setScheduleRelationship(java.lang.CharSequence value) {
    this.scheduleRelationship = value;
  }

  /**
   * Gets the value of the 'routeId' field.
   * @return The value of the 'routeId' field.
   */
  public java.lang.CharSequence getRouteId() {
    return routeId;
  }


  /**
   * Sets the value of the 'routeId' field.
   * @param value the value to set.
   */
  public void setRouteId(java.lang.CharSequence value) {
    this.routeId = value;
  }

  /**
   * Gets the value of the 'vehicleTimestamp' field.
   * @return The value of the 'vehicleTimestamp' field.
   */
  public java.lang.CharSequence getVehicleTimestamp() {
    return vehicleTimestamp;
  }


  /**
   * Sets the value of the 'vehicleTimestamp' field.
   * @param value the value to set.
   */
  public void setVehicleTimestamp(java.lang.CharSequence value) {
    this.vehicleTimestamp = value;
  }

  /**
   * Creates a new VehicleEvent RecordBuilder.
   * @return A new VehicleEvent RecordBuilder
   */
  public static VehicleEvent.Builder newBuilder() {
    return new VehicleEvent.Builder();
  }

  /**
   * Creates a new VehicleEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VehicleEvent RecordBuilder
   */
  public static VehicleEvent.Builder newBuilder(VehicleEvent.Builder other) {
    if (other == null) {
      return new VehicleEvent.Builder();
    } else {
      return new VehicleEvent.Builder(other);
    }
  }

  /**
   * Creates a new VehicleEvent RecordBuilder by copying an existing VehicleEvent instance.
   * @param other The existing instance to copy.
   * @return A new VehicleEvent RecordBuilder
   */
  public static VehicleEvent.Builder newBuilder(VehicleEvent other) {
    if (other == null) {
      return new VehicleEvent.Builder();
    } else {
      return new VehicleEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for VehicleEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VehicleEvent>
    implements org.apache.avro.data.RecordBuilder<VehicleEvent> {

    private java.lang.CharSequence tripId;
    private java.lang.CharSequence startTime;
    private java.lang.CharSequence startData;
    private java.lang.CharSequence scheduleRelationship;
    private java.lang.CharSequence routeId;
    private java.lang.CharSequence vehicleTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(VehicleEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tripId)) {
        this.tripId = data().deepCopy(fields()[0].schema(), other.tripId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.startTime)) {
        this.startTime = data().deepCopy(fields()[1].schema(), other.startTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.startData)) {
        this.startData = data().deepCopy(fields()[2].schema(), other.startData);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.scheduleRelationship)) {
        this.scheduleRelationship = data().deepCopy(fields()[3].schema(), other.scheduleRelationship);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.routeId)) {
        this.routeId = data().deepCopy(fields()[4].schema(), other.routeId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.vehicleTimestamp)) {
        this.vehicleTimestamp = data().deepCopy(fields()[5].schema(), other.vehicleTimestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing VehicleEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(VehicleEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.tripId)) {
        this.tripId = data().deepCopy(fields()[0].schema(), other.tripId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startTime)) {
        this.startTime = data().deepCopy(fields()[1].schema(), other.startTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.startData)) {
        this.startData = data().deepCopy(fields()[2].schema(), other.startData);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.scheduleRelationship)) {
        this.scheduleRelationship = data().deepCopy(fields()[3].schema(), other.scheduleRelationship);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.routeId)) {
        this.routeId = data().deepCopy(fields()[4].schema(), other.routeId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.vehicleTimestamp)) {
        this.vehicleTimestamp = data().deepCopy(fields()[5].schema(), other.vehicleTimestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'tripId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTripId() {
      return tripId;
    }


    /**
      * Sets the value of the 'tripId' field.
      * @param value The value of 'tripId'.
      * @return This builder.
      */
    public VehicleEvent.Builder setTripId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tripId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tripId' field has been set.
      * @return True if the 'tripId' field has been set, false otherwise.
      */
    public boolean hasTripId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tripId' field.
      * @return This builder.
      */
    public VehicleEvent.Builder clearTripId() {
      tripId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'startTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartTime() {
      return startTime;
    }


    /**
      * Sets the value of the 'startTime' field.
      * @param value The value of 'startTime'.
      * @return This builder.
      */
    public VehicleEvent.Builder setStartTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.startTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'startTime' field has been set.
      * @return True if the 'startTime' field has been set, false otherwise.
      */
    public boolean hasStartTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'startTime' field.
      * @return This builder.
      */
    public VehicleEvent.Builder clearStartTime() {
      startTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'startData' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartData() {
      return startData;
    }


    /**
      * Sets the value of the 'startData' field.
      * @param value The value of 'startData'.
      * @return This builder.
      */
    public VehicleEvent.Builder setStartData(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.startData = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'startData' field has been set.
      * @return True if the 'startData' field has been set, false otherwise.
      */
    public boolean hasStartData() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'startData' field.
      * @return This builder.
      */
    public VehicleEvent.Builder clearStartData() {
      startData = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'scheduleRelationship' field.
      * @return The value.
      */
    public java.lang.CharSequence getScheduleRelationship() {
      return scheduleRelationship;
    }


    /**
      * Sets the value of the 'scheduleRelationship' field.
      * @param value The value of 'scheduleRelationship'.
      * @return This builder.
      */
    public VehicleEvent.Builder setScheduleRelationship(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.scheduleRelationship = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'scheduleRelationship' field has been set.
      * @return True if the 'scheduleRelationship' field has been set, false otherwise.
      */
    public boolean hasScheduleRelationship() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'scheduleRelationship' field.
      * @return This builder.
      */
    public VehicleEvent.Builder clearScheduleRelationship() {
      scheduleRelationship = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'routeId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRouteId() {
      return routeId;
    }


    /**
      * Sets the value of the 'routeId' field.
      * @param value The value of 'routeId'.
      * @return This builder.
      */
    public VehicleEvent.Builder setRouteId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.routeId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'routeId' field has been set.
      * @return True if the 'routeId' field has been set, false otherwise.
      */
    public boolean hasRouteId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'routeId' field.
      * @return This builder.
      */
    public VehicleEvent.Builder clearRouteId() {
      routeId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehicleTimestamp' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehicleTimestamp() {
      return vehicleTimestamp;
    }


    /**
      * Sets the value of the 'vehicleTimestamp' field.
      * @param value The value of 'vehicleTimestamp'.
      * @return This builder.
      */
    public VehicleEvent.Builder setVehicleTimestamp(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.vehicleTimestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleTimestamp' field has been set.
      * @return True if the 'vehicleTimestamp' field has been set, false otherwise.
      */
    public boolean hasVehicleTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'vehicleTimestamp' field.
      * @return This builder.
      */
    public VehicleEvent.Builder clearVehicleTimestamp() {
      vehicleTimestamp = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VehicleEvent build() {
      try {
        VehicleEvent record = new VehicleEvent();
        record.tripId = fieldSetFlags()[0] ? this.tripId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.startTime = fieldSetFlags()[1] ? this.startTime : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.startData = fieldSetFlags()[2] ? this.startData : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.scheduleRelationship = fieldSetFlags()[3] ? this.scheduleRelationship : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.routeId = fieldSetFlags()[4] ? this.routeId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.vehicleTimestamp = fieldSetFlags()[5] ? this.vehicleTimestamp : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VehicleEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<VehicleEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VehicleEvent>
    READER$ = (org.apache.avro.io.DatumReader<VehicleEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tripId);

    out.writeString(this.startTime);

    out.writeString(this.startData);

    out.writeString(this.scheduleRelationship);

    out.writeString(this.routeId);

    out.writeString(this.vehicleTimestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);

      this.startTime = in.readString(this.startTime instanceof Utf8 ? (Utf8)this.startTime : null);

      this.startData = in.readString(this.startData instanceof Utf8 ? (Utf8)this.startData : null);

      this.scheduleRelationship = in.readString(this.scheduleRelationship instanceof Utf8 ? (Utf8)this.scheduleRelationship : null);

      this.routeId = in.readString(this.routeId instanceof Utf8 ? (Utf8)this.routeId : null);

      this.vehicleTimestamp = in.readString(this.vehicleTimestamp instanceof Utf8 ? (Utf8)this.vehicleTimestamp : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);
          break;

        case 1:
          this.startTime = in.readString(this.startTime instanceof Utf8 ? (Utf8)this.startTime : null);
          break;

        case 2:
          this.startData = in.readString(this.startData instanceof Utf8 ? (Utf8)this.startData : null);
          break;

        case 3:
          this.scheduleRelationship = in.readString(this.scheduleRelationship instanceof Utf8 ? (Utf8)this.scheduleRelationship : null);
          break;

        case 4:
          this.routeId = in.readString(this.routeId instanceof Utf8 ? (Utf8)this.routeId : null);
          break;

        case 5:
          this.vehicleTimestamp = in.readString(this.vehicleTimestamp instanceof Utf8 ? (Utf8)this.vehicleTimestamp : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










