/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fyp.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroRouteMetric extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8658818306895490063L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroRouteMetric\",\"namespace\":\"com.fyp.avro\",\"fields\":[{\"name\":\"routeId\",\"type\":\"string\"},{\"name\":\"windowStart\",\"type\":\"long\"},{\"name\":\"windowEnd\",\"type\":\"long\"},{\"name\":\"delayCount\",\"type\":\"long\"},{\"name\":\"maxArrivalDelay\",\"type\":\"long\"},{\"name\":\"minArrivalDelay\",\"type\":\"long\"},{\"name\":\"maxDepartureDelay\",\"type\":\"long\"},{\"name\":\"minDepartureDelay\",\"type\":\"long\"},{\"name\":\"totalDepartureDelay\",\"type\":\"long\"},{\"name\":\"totalArrivalDelay\",\"type\":\"long\"},{\"name\":\"avgArrivalDelay\",\"type\":\"double\"},{\"name\":\"avgDepartureDelay\",\"type\":\"double\"},{\"name\":\"totalOverallDelay\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroRouteMetric> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroRouteMetric> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroRouteMetric> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroRouteMetric> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroRouteMetric> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroRouteMetric to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroRouteMetric from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroRouteMetric instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroRouteMetric fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence routeId;
  private long windowStart;
  private long windowEnd;
  private long delayCount;
  private long maxArrivalDelay;
  private long minArrivalDelay;
  private long maxDepartureDelay;
  private long minDepartureDelay;
  private long totalDepartureDelay;
  private long totalArrivalDelay;
  private double avgArrivalDelay;
  private double avgDepartureDelay;
  private long totalOverallDelay;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroRouteMetric() {}

  /**
   * All-args constructor.
   * @param routeId The new value for routeId
   * @param windowStart The new value for windowStart
   * @param windowEnd The new value for windowEnd
   * @param delayCount The new value for delayCount
   * @param maxArrivalDelay The new value for maxArrivalDelay
   * @param minArrivalDelay The new value for minArrivalDelay
   * @param maxDepartureDelay The new value for maxDepartureDelay
   * @param minDepartureDelay The new value for minDepartureDelay
   * @param totalDepartureDelay The new value for totalDepartureDelay
   * @param totalArrivalDelay The new value for totalArrivalDelay
   * @param avgArrivalDelay The new value for avgArrivalDelay
   * @param avgDepartureDelay The new value for avgDepartureDelay
   * @param totalOverallDelay The new value for totalOverallDelay
   */
  public AvroRouteMetric(java.lang.CharSequence routeId, java.lang.Long windowStart, java.lang.Long windowEnd, java.lang.Long delayCount, java.lang.Long maxArrivalDelay, java.lang.Long minArrivalDelay, java.lang.Long maxDepartureDelay, java.lang.Long minDepartureDelay, java.lang.Long totalDepartureDelay, java.lang.Long totalArrivalDelay, java.lang.Double avgArrivalDelay, java.lang.Double avgDepartureDelay, java.lang.Long totalOverallDelay) {
    this.routeId = routeId;
    this.windowStart = windowStart;
    this.windowEnd = windowEnd;
    this.delayCount = delayCount;
    this.maxArrivalDelay = maxArrivalDelay;
    this.minArrivalDelay = minArrivalDelay;
    this.maxDepartureDelay = maxDepartureDelay;
    this.minDepartureDelay = minDepartureDelay;
    this.totalDepartureDelay = totalDepartureDelay;
    this.totalArrivalDelay = totalArrivalDelay;
    this.avgArrivalDelay = avgArrivalDelay;
    this.avgDepartureDelay = avgDepartureDelay;
    this.totalOverallDelay = totalOverallDelay;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return routeId;
    case 1: return windowStart;
    case 2: return windowEnd;
    case 3: return delayCount;
    case 4: return maxArrivalDelay;
    case 5: return minArrivalDelay;
    case 6: return maxDepartureDelay;
    case 7: return minDepartureDelay;
    case 8: return totalDepartureDelay;
    case 9: return totalArrivalDelay;
    case 10: return avgArrivalDelay;
    case 11: return avgDepartureDelay;
    case 12: return totalOverallDelay;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: routeId = (java.lang.CharSequence)value$; break;
    case 1: windowStart = (java.lang.Long)value$; break;
    case 2: windowEnd = (java.lang.Long)value$; break;
    case 3: delayCount = (java.lang.Long)value$; break;
    case 4: maxArrivalDelay = (java.lang.Long)value$; break;
    case 5: minArrivalDelay = (java.lang.Long)value$; break;
    case 6: maxDepartureDelay = (java.lang.Long)value$; break;
    case 7: minDepartureDelay = (java.lang.Long)value$; break;
    case 8: totalDepartureDelay = (java.lang.Long)value$; break;
    case 9: totalArrivalDelay = (java.lang.Long)value$; break;
    case 10: avgArrivalDelay = (java.lang.Double)value$; break;
    case 11: avgDepartureDelay = (java.lang.Double)value$; break;
    case 12: totalOverallDelay = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'routeId' field.
   * @return The value of the 'routeId' field.
   */
  public java.lang.CharSequence getRouteId() {
    return routeId;
  }


  /**
   * Sets the value of the 'routeId' field.
   * @param value the value to set.
   */
  public void setRouteId(java.lang.CharSequence value) {
    this.routeId = value;
  }

  /**
   * Gets the value of the 'windowStart' field.
   * @return The value of the 'windowStart' field.
   */
  public long getWindowStart() {
    return windowStart;
  }


  /**
   * Sets the value of the 'windowStart' field.
   * @param value the value to set.
   */
  public void setWindowStart(long value) {
    this.windowStart = value;
  }

  /**
   * Gets the value of the 'windowEnd' field.
   * @return The value of the 'windowEnd' field.
   */
  public long getWindowEnd() {
    return windowEnd;
  }


  /**
   * Sets the value of the 'windowEnd' field.
   * @param value the value to set.
   */
  public void setWindowEnd(long value) {
    this.windowEnd = value;
  }

  /**
   * Gets the value of the 'delayCount' field.
   * @return The value of the 'delayCount' field.
   */
  public long getDelayCount() {
    return delayCount;
  }


  /**
   * Sets the value of the 'delayCount' field.
   * @param value the value to set.
   */
  public void setDelayCount(long value) {
    this.delayCount = value;
  }

  /**
   * Gets the value of the 'maxArrivalDelay' field.
   * @return The value of the 'maxArrivalDelay' field.
   */
  public long getMaxArrivalDelay() {
    return maxArrivalDelay;
  }


  /**
   * Sets the value of the 'maxArrivalDelay' field.
   * @param value the value to set.
   */
  public void setMaxArrivalDelay(long value) {
    this.maxArrivalDelay = value;
  }

  /**
   * Gets the value of the 'minArrivalDelay' field.
   * @return The value of the 'minArrivalDelay' field.
   */
  public long getMinArrivalDelay() {
    return minArrivalDelay;
  }


  /**
   * Sets the value of the 'minArrivalDelay' field.
   * @param value the value to set.
   */
  public void setMinArrivalDelay(long value) {
    this.minArrivalDelay = value;
  }

  /**
   * Gets the value of the 'maxDepartureDelay' field.
   * @return The value of the 'maxDepartureDelay' field.
   */
  public long getMaxDepartureDelay() {
    return maxDepartureDelay;
  }


  /**
   * Sets the value of the 'maxDepartureDelay' field.
   * @param value the value to set.
   */
  public void setMaxDepartureDelay(long value) {
    this.maxDepartureDelay = value;
  }

  /**
   * Gets the value of the 'minDepartureDelay' field.
   * @return The value of the 'minDepartureDelay' field.
   */
  public long getMinDepartureDelay() {
    return minDepartureDelay;
  }


  /**
   * Sets the value of the 'minDepartureDelay' field.
   * @param value the value to set.
   */
  public void setMinDepartureDelay(long value) {
    this.minDepartureDelay = value;
  }

  /**
   * Gets the value of the 'totalDepartureDelay' field.
   * @return The value of the 'totalDepartureDelay' field.
   */
  public long getTotalDepartureDelay() {
    return totalDepartureDelay;
  }


  /**
   * Sets the value of the 'totalDepartureDelay' field.
   * @param value the value to set.
   */
  public void setTotalDepartureDelay(long value) {
    this.totalDepartureDelay = value;
  }

  /**
   * Gets the value of the 'totalArrivalDelay' field.
   * @return The value of the 'totalArrivalDelay' field.
   */
  public long getTotalArrivalDelay() {
    return totalArrivalDelay;
  }


  /**
   * Sets the value of the 'totalArrivalDelay' field.
   * @param value the value to set.
   */
  public void setTotalArrivalDelay(long value) {
    this.totalArrivalDelay = value;
  }

  /**
   * Gets the value of the 'avgArrivalDelay' field.
   * @return The value of the 'avgArrivalDelay' field.
   */
  public double getAvgArrivalDelay() {
    return avgArrivalDelay;
  }


  /**
   * Sets the value of the 'avgArrivalDelay' field.
   * @param value the value to set.
   */
  public void setAvgArrivalDelay(double value) {
    this.avgArrivalDelay = value;
  }

  /**
   * Gets the value of the 'avgDepartureDelay' field.
   * @return The value of the 'avgDepartureDelay' field.
   */
  public double getAvgDepartureDelay() {
    return avgDepartureDelay;
  }


  /**
   * Sets the value of the 'avgDepartureDelay' field.
   * @param value the value to set.
   */
  public void setAvgDepartureDelay(double value) {
    this.avgDepartureDelay = value;
  }

  /**
   * Gets the value of the 'totalOverallDelay' field.
   * @return The value of the 'totalOverallDelay' field.
   */
  public long getTotalOverallDelay() {
    return totalOverallDelay;
  }


  /**
   * Sets the value of the 'totalOverallDelay' field.
   * @param value the value to set.
   */
  public void setTotalOverallDelay(long value) {
    this.totalOverallDelay = value;
  }

  /**
   * Creates a new AvroRouteMetric RecordBuilder.
   * @return A new AvroRouteMetric RecordBuilder
   */
  public static com.fyp.avro.AvroRouteMetric.Builder newBuilder() {
    return new com.fyp.avro.AvroRouteMetric.Builder();
  }

  /**
   * Creates a new AvroRouteMetric RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroRouteMetric RecordBuilder
   */
  public static com.fyp.avro.AvroRouteMetric.Builder newBuilder(com.fyp.avro.AvroRouteMetric.Builder other) {
    if (other == null) {
      return new com.fyp.avro.AvroRouteMetric.Builder();
    } else {
      return new com.fyp.avro.AvroRouteMetric.Builder(other);
    }
  }

  /**
   * Creates a new AvroRouteMetric RecordBuilder by copying an existing AvroRouteMetric instance.
   * @param other The existing instance to copy.
   * @return A new AvroRouteMetric RecordBuilder
   */
  public static com.fyp.avro.AvroRouteMetric.Builder newBuilder(com.fyp.avro.AvroRouteMetric other) {
    if (other == null) {
      return new com.fyp.avro.AvroRouteMetric.Builder();
    } else {
      return new com.fyp.avro.AvroRouteMetric.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroRouteMetric instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroRouteMetric>
    implements org.apache.avro.data.RecordBuilder<AvroRouteMetric> {

    private java.lang.CharSequence routeId;
    private long windowStart;
    private long windowEnd;
    private long delayCount;
    private long maxArrivalDelay;
    private long minArrivalDelay;
    private long maxDepartureDelay;
    private long minDepartureDelay;
    private long totalDepartureDelay;
    private long totalArrivalDelay;
    private double avgArrivalDelay;
    private double avgDepartureDelay;
    private long totalOverallDelay;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fyp.avro.AvroRouteMetric.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.routeId)) {
        this.routeId = data().deepCopy(fields()[0].schema(), other.routeId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.windowStart)) {
        this.windowStart = data().deepCopy(fields()[1].schema(), other.windowStart);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.windowEnd)) {
        this.windowEnd = data().deepCopy(fields()[2].schema(), other.windowEnd);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.delayCount)) {
        this.delayCount = data().deepCopy(fields()[3].schema(), other.delayCount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.maxArrivalDelay)) {
        this.maxArrivalDelay = data().deepCopy(fields()[4].schema(), other.maxArrivalDelay);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.minArrivalDelay)) {
        this.minArrivalDelay = data().deepCopy(fields()[5].schema(), other.minArrivalDelay);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.maxDepartureDelay)) {
        this.maxDepartureDelay = data().deepCopy(fields()[6].schema(), other.maxDepartureDelay);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.minDepartureDelay)) {
        this.minDepartureDelay = data().deepCopy(fields()[7].schema(), other.minDepartureDelay);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.totalDepartureDelay)) {
        this.totalDepartureDelay = data().deepCopy(fields()[8].schema(), other.totalDepartureDelay);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.totalArrivalDelay)) {
        this.totalArrivalDelay = data().deepCopy(fields()[9].schema(), other.totalArrivalDelay);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.avgArrivalDelay)) {
        this.avgArrivalDelay = data().deepCopy(fields()[10].schema(), other.avgArrivalDelay);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.avgDepartureDelay)) {
        this.avgDepartureDelay = data().deepCopy(fields()[11].schema(), other.avgDepartureDelay);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.totalOverallDelay)) {
        this.totalOverallDelay = data().deepCopy(fields()[12].schema(), other.totalOverallDelay);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroRouteMetric instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fyp.avro.AvroRouteMetric other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.routeId)) {
        this.routeId = data().deepCopy(fields()[0].schema(), other.routeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.windowStart)) {
        this.windowStart = data().deepCopy(fields()[1].schema(), other.windowStart);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.windowEnd)) {
        this.windowEnd = data().deepCopy(fields()[2].schema(), other.windowEnd);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.delayCount)) {
        this.delayCount = data().deepCopy(fields()[3].schema(), other.delayCount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.maxArrivalDelay)) {
        this.maxArrivalDelay = data().deepCopy(fields()[4].schema(), other.maxArrivalDelay);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.minArrivalDelay)) {
        this.minArrivalDelay = data().deepCopy(fields()[5].schema(), other.minArrivalDelay);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.maxDepartureDelay)) {
        this.maxDepartureDelay = data().deepCopy(fields()[6].schema(), other.maxDepartureDelay);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.minDepartureDelay)) {
        this.minDepartureDelay = data().deepCopy(fields()[7].schema(), other.minDepartureDelay);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.totalDepartureDelay)) {
        this.totalDepartureDelay = data().deepCopy(fields()[8].schema(), other.totalDepartureDelay);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.totalArrivalDelay)) {
        this.totalArrivalDelay = data().deepCopy(fields()[9].schema(), other.totalArrivalDelay);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.avgArrivalDelay)) {
        this.avgArrivalDelay = data().deepCopy(fields()[10].schema(), other.avgArrivalDelay);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.avgDepartureDelay)) {
        this.avgDepartureDelay = data().deepCopy(fields()[11].schema(), other.avgDepartureDelay);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.totalOverallDelay)) {
        this.totalOverallDelay = data().deepCopy(fields()[12].schema(), other.totalOverallDelay);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'routeId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRouteId() {
      return routeId;
    }


    /**
      * Sets the value of the 'routeId' field.
      * @param value The value of 'routeId'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setRouteId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.routeId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'routeId' field has been set.
      * @return True if the 'routeId' field has been set, false otherwise.
      */
    public boolean hasRouteId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'routeId' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearRouteId() {
      routeId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'windowStart' field.
      * @return The value.
      */
    public long getWindowStart() {
      return windowStart;
    }


    /**
      * Sets the value of the 'windowStart' field.
      * @param value The value of 'windowStart'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setWindowStart(long value) {
      validate(fields()[1], value);
      this.windowStart = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'windowStart' field has been set.
      * @return True if the 'windowStart' field has been set, false otherwise.
      */
    public boolean hasWindowStart() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'windowStart' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearWindowStart() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'windowEnd' field.
      * @return The value.
      */
    public long getWindowEnd() {
      return windowEnd;
    }


    /**
      * Sets the value of the 'windowEnd' field.
      * @param value The value of 'windowEnd'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setWindowEnd(long value) {
      validate(fields()[2], value);
      this.windowEnd = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'windowEnd' field has been set.
      * @return True if the 'windowEnd' field has been set, false otherwise.
      */
    public boolean hasWindowEnd() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'windowEnd' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearWindowEnd() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'delayCount' field.
      * @return The value.
      */
    public long getDelayCount() {
      return delayCount;
    }


    /**
      * Sets the value of the 'delayCount' field.
      * @param value The value of 'delayCount'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setDelayCount(long value) {
      validate(fields()[3], value);
      this.delayCount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'delayCount' field has been set.
      * @return True if the 'delayCount' field has been set, false otherwise.
      */
    public boolean hasDelayCount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'delayCount' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearDelayCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'maxArrivalDelay' field.
      * @return The value.
      */
    public long getMaxArrivalDelay() {
      return maxArrivalDelay;
    }


    /**
      * Sets the value of the 'maxArrivalDelay' field.
      * @param value The value of 'maxArrivalDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setMaxArrivalDelay(long value) {
      validate(fields()[4], value);
      this.maxArrivalDelay = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'maxArrivalDelay' field has been set.
      * @return True if the 'maxArrivalDelay' field has been set, false otherwise.
      */
    public boolean hasMaxArrivalDelay() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'maxArrivalDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearMaxArrivalDelay() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'minArrivalDelay' field.
      * @return The value.
      */
    public long getMinArrivalDelay() {
      return minArrivalDelay;
    }


    /**
      * Sets the value of the 'minArrivalDelay' field.
      * @param value The value of 'minArrivalDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setMinArrivalDelay(long value) {
      validate(fields()[5], value);
      this.minArrivalDelay = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'minArrivalDelay' field has been set.
      * @return True if the 'minArrivalDelay' field has been set, false otherwise.
      */
    public boolean hasMinArrivalDelay() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'minArrivalDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearMinArrivalDelay() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'maxDepartureDelay' field.
      * @return The value.
      */
    public long getMaxDepartureDelay() {
      return maxDepartureDelay;
    }


    /**
      * Sets the value of the 'maxDepartureDelay' field.
      * @param value The value of 'maxDepartureDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setMaxDepartureDelay(long value) {
      validate(fields()[6], value);
      this.maxDepartureDelay = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'maxDepartureDelay' field has been set.
      * @return True if the 'maxDepartureDelay' field has been set, false otherwise.
      */
    public boolean hasMaxDepartureDelay() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'maxDepartureDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearMaxDepartureDelay() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'minDepartureDelay' field.
      * @return The value.
      */
    public long getMinDepartureDelay() {
      return minDepartureDelay;
    }


    /**
      * Sets the value of the 'minDepartureDelay' field.
      * @param value The value of 'minDepartureDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setMinDepartureDelay(long value) {
      validate(fields()[7], value);
      this.minDepartureDelay = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'minDepartureDelay' field has been set.
      * @return True if the 'minDepartureDelay' field has been set, false otherwise.
      */
    public boolean hasMinDepartureDelay() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'minDepartureDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearMinDepartureDelay() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalDepartureDelay' field.
      * @return The value.
      */
    public long getTotalDepartureDelay() {
      return totalDepartureDelay;
    }


    /**
      * Sets the value of the 'totalDepartureDelay' field.
      * @param value The value of 'totalDepartureDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setTotalDepartureDelay(long value) {
      validate(fields()[8], value);
      this.totalDepartureDelay = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'totalDepartureDelay' field has been set.
      * @return True if the 'totalDepartureDelay' field has been set, false otherwise.
      */
    public boolean hasTotalDepartureDelay() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'totalDepartureDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearTotalDepartureDelay() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalArrivalDelay' field.
      * @return The value.
      */
    public long getTotalArrivalDelay() {
      return totalArrivalDelay;
    }


    /**
      * Sets the value of the 'totalArrivalDelay' field.
      * @param value The value of 'totalArrivalDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setTotalArrivalDelay(long value) {
      validate(fields()[9], value);
      this.totalArrivalDelay = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'totalArrivalDelay' field has been set.
      * @return True if the 'totalArrivalDelay' field has been set, false otherwise.
      */
    public boolean hasTotalArrivalDelay() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'totalArrivalDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearTotalArrivalDelay() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'avgArrivalDelay' field.
      * @return The value.
      */
    public double getAvgArrivalDelay() {
      return avgArrivalDelay;
    }


    /**
      * Sets the value of the 'avgArrivalDelay' field.
      * @param value The value of 'avgArrivalDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setAvgArrivalDelay(double value) {
      validate(fields()[10], value);
      this.avgArrivalDelay = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'avgArrivalDelay' field has been set.
      * @return True if the 'avgArrivalDelay' field has been set, false otherwise.
      */
    public boolean hasAvgArrivalDelay() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'avgArrivalDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearAvgArrivalDelay() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'avgDepartureDelay' field.
      * @return The value.
      */
    public double getAvgDepartureDelay() {
      return avgDepartureDelay;
    }


    /**
      * Sets the value of the 'avgDepartureDelay' field.
      * @param value The value of 'avgDepartureDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setAvgDepartureDelay(double value) {
      validate(fields()[11], value);
      this.avgDepartureDelay = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'avgDepartureDelay' field has been set.
      * @return True if the 'avgDepartureDelay' field has been set, false otherwise.
      */
    public boolean hasAvgDepartureDelay() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'avgDepartureDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearAvgDepartureDelay() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalOverallDelay' field.
      * @return The value.
      */
    public long getTotalOverallDelay() {
      return totalOverallDelay;
    }


    /**
      * Sets the value of the 'totalOverallDelay' field.
      * @param value The value of 'totalOverallDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder setTotalOverallDelay(long value) {
      validate(fields()[12], value);
      this.totalOverallDelay = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'totalOverallDelay' field has been set.
      * @return True if the 'totalOverallDelay' field has been set, false otherwise.
      */
    public boolean hasTotalOverallDelay() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'totalOverallDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroRouteMetric.Builder clearTotalOverallDelay() {
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroRouteMetric build() {
      try {
        AvroRouteMetric record = new AvroRouteMetric();
        record.routeId = fieldSetFlags()[0] ? this.routeId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.windowStart = fieldSetFlags()[1] ? this.windowStart : (java.lang.Long) defaultValue(fields()[1]);
        record.windowEnd = fieldSetFlags()[2] ? this.windowEnd : (java.lang.Long) defaultValue(fields()[2]);
        record.delayCount = fieldSetFlags()[3] ? this.delayCount : (java.lang.Long) defaultValue(fields()[3]);
        record.maxArrivalDelay = fieldSetFlags()[4] ? this.maxArrivalDelay : (java.lang.Long) defaultValue(fields()[4]);
        record.minArrivalDelay = fieldSetFlags()[5] ? this.minArrivalDelay : (java.lang.Long) defaultValue(fields()[5]);
        record.maxDepartureDelay = fieldSetFlags()[6] ? this.maxDepartureDelay : (java.lang.Long) defaultValue(fields()[6]);
        record.minDepartureDelay = fieldSetFlags()[7] ? this.minDepartureDelay : (java.lang.Long) defaultValue(fields()[7]);
        record.totalDepartureDelay = fieldSetFlags()[8] ? this.totalDepartureDelay : (java.lang.Long) defaultValue(fields()[8]);
        record.totalArrivalDelay = fieldSetFlags()[9] ? this.totalArrivalDelay : (java.lang.Long) defaultValue(fields()[9]);
        record.avgArrivalDelay = fieldSetFlags()[10] ? this.avgArrivalDelay : (java.lang.Double) defaultValue(fields()[10]);
        record.avgDepartureDelay = fieldSetFlags()[11] ? this.avgDepartureDelay : (java.lang.Double) defaultValue(fields()[11]);
        record.totalOverallDelay = fieldSetFlags()[12] ? this.totalOverallDelay : (java.lang.Long) defaultValue(fields()[12]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroRouteMetric>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroRouteMetric>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroRouteMetric>
    READER$ = (org.apache.avro.io.DatumReader<AvroRouteMetric>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.routeId);

    out.writeLong(this.windowStart);

    out.writeLong(this.windowEnd);

    out.writeLong(this.delayCount);

    out.writeLong(this.maxArrivalDelay);

    out.writeLong(this.minArrivalDelay);

    out.writeLong(this.maxDepartureDelay);

    out.writeLong(this.minDepartureDelay);

    out.writeLong(this.totalDepartureDelay);

    out.writeLong(this.totalArrivalDelay);

    out.writeDouble(this.avgArrivalDelay);

    out.writeDouble(this.avgDepartureDelay);

    out.writeLong(this.totalOverallDelay);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.routeId = in.readString(this.routeId instanceof Utf8 ? (Utf8)this.routeId : null);

      this.windowStart = in.readLong();

      this.windowEnd = in.readLong();

      this.delayCount = in.readLong();

      this.maxArrivalDelay = in.readLong();

      this.minArrivalDelay = in.readLong();

      this.maxDepartureDelay = in.readLong();

      this.minDepartureDelay = in.readLong();

      this.totalDepartureDelay = in.readLong();

      this.totalArrivalDelay = in.readLong();

      this.avgArrivalDelay = in.readDouble();

      this.avgDepartureDelay = in.readDouble();

      this.totalOverallDelay = in.readLong();

    } else {
      for (int i = 0; i < 13; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.routeId = in.readString(this.routeId instanceof Utf8 ? (Utf8)this.routeId : null);
          break;

        case 1:
          this.windowStart = in.readLong();
          break;

        case 2:
          this.windowEnd = in.readLong();
          break;

        case 3:
          this.delayCount = in.readLong();
          break;

        case 4:
          this.maxArrivalDelay = in.readLong();
          break;

        case 5:
          this.minArrivalDelay = in.readLong();
          break;

        case 6:
          this.maxDepartureDelay = in.readLong();
          break;

        case 7:
          this.minDepartureDelay = in.readLong();
          break;

        case 8:
          this.totalDepartureDelay = in.readLong();
          break;

        case 9:
          this.totalArrivalDelay = in.readLong();
          break;

        case 10:
          this.avgArrivalDelay = in.readDouble();
          break;

        case 11:
          this.avgDepartureDelay = in.readDouble();
          break;

        case 12:
          this.totalOverallDelay = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










