/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fyp.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroStopTimeUpdate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2267633113104478779L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroStopTimeUpdate\",\"namespace\":\"com.fyp.avro\",\"fields\":[{\"name\":\"stopSequence\",\"type\":\"string\"},{\"name\":\"aDelay\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"dDelay\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"stopId\",\"type\":\"string\"},{\"name\":\"stopTimeUpdateScheduleRelationship\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroStopTimeUpdate> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroStopTimeUpdate> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroStopTimeUpdate> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroStopTimeUpdate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroStopTimeUpdate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroStopTimeUpdate to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroStopTimeUpdate from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroStopTimeUpdate instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroStopTimeUpdate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence stopSequence;
  private java.lang.Integer aDelay;
  private java.lang.Integer dDelay;
  private java.lang.CharSequence stopId;
  private java.lang.CharSequence stopTimeUpdateScheduleRelationship;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroStopTimeUpdate() {}

  /**
   * All-args constructor.
   * @param stopSequence The new value for stopSequence
   * @param aDelay The new value for aDelay
   * @param dDelay The new value for dDelay
   * @param stopId The new value for stopId
   * @param stopTimeUpdateScheduleRelationship The new value for stopTimeUpdateScheduleRelationship
   */
  public AvroStopTimeUpdate(java.lang.CharSequence stopSequence, java.lang.Integer aDelay, java.lang.Integer dDelay, java.lang.CharSequence stopId, java.lang.CharSequence stopTimeUpdateScheduleRelationship) {
    this.stopSequence = stopSequence;
    this.aDelay = aDelay;
    this.dDelay = dDelay;
    this.stopId = stopId;
    this.stopTimeUpdateScheduleRelationship = stopTimeUpdateScheduleRelationship;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stopSequence;
    case 1: return aDelay;
    case 2: return dDelay;
    case 3: return stopId;
    case 4: return stopTimeUpdateScheduleRelationship;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stopSequence = (java.lang.CharSequence)value$; break;
    case 1: aDelay = (java.lang.Integer)value$; break;
    case 2: dDelay = (java.lang.Integer)value$; break;
    case 3: stopId = (java.lang.CharSequence)value$; break;
    case 4: stopTimeUpdateScheduleRelationship = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'stopSequence' field.
   * @return The value of the 'stopSequence' field.
   */
  public java.lang.CharSequence getStopSequence() {
    return stopSequence;
  }


  /**
   * Sets the value of the 'stopSequence' field.
   * @param value the value to set.
   */
  public void setStopSequence(java.lang.CharSequence value) {
    this.stopSequence = value;
  }

  /**
   * Gets the value of the 'aDelay' field.
   * @return The value of the 'aDelay' field.
   */
  public java.lang.Integer getADelay() {
    return aDelay;
  }


  /**
   * Sets the value of the 'aDelay' field.
   * @param value the value to set.
   */
  public void setADelay(java.lang.Integer value) {
    this.aDelay = value;
  }

  /**
   * Gets the value of the 'dDelay' field.
   * @return The value of the 'dDelay' field.
   */
  public java.lang.Integer getDDelay() {
    return dDelay;
  }


  /**
   * Sets the value of the 'dDelay' field.
   * @param value the value to set.
   */
  public void setDDelay(java.lang.Integer value) {
    this.dDelay = value;
  }

  /**
   * Gets the value of the 'stopId' field.
   * @return The value of the 'stopId' field.
   */
  public java.lang.CharSequence getStopId() {
    return stopId;
  }


  /**
   * Sets the value of the 'stopId' field.
   * @param value the value to set.
   */
  public void setStopId(java.lang.CharSequence value) {
    this.stopId = value;
  }

  /**
   * Gets the value of the 'stopTimeUpdateScheduleRelationship' field.
   * @return The value of the 'stopTimeUpdateScheduleRelationship' field.
   */
  public java.lang.CharSequence getStopTimeUpdateScheduleRelationship() {
    return stopTimeUpdateScheduleRelationship;
  }


  /**
   * Sets the value of the 'stopTimeUpdateScheduleRelationship' field.
   * @param value the value to set.
   */
  public void setStopTimeUpdateScheduleRelationship(java.lang.CharSequence value) {
    this.stopTimeUpdateScheduleRelationship = value;
  }

  /**
   * Creates a new AvroStopTimeUpdate RecordBuilder.
   * @return A new AvroStopTimeUpdate RecordBuilder
   */
  public static com.fyp.avro.AvroStopTimeUpdate.Builder newBuilder() {
    return new com.fyp.avro.AvroStopTimeUpdate.Builder();
  }

  /**
   * Creates a new AvroStopTimeUpdate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroStopTimeUpdate RecordBuilder
   */
  public static com.fyp.avro.AvroStopTimeUpdate.Builder newBuilder(com.fyp.avro.AvroStopTimeUpdate.Builder other) {
    if (other == null) {
      return new com.fyp.avro.AvroStopTimeUpdate.Builder();
    } else {
      return new com.fyp.avro.AvroStopTimeUpdate.Builder(other);
    }
  }

  /**
   * Creates a new AvroStopTimeUpdate RecordBuilder by copying an existing AvroStopTimeUpdate instance.
   * @param other The existing instance to copy.
   * @return A new AvroStopTimeUpdate RecordBuilder
   */
  public static com.fyp.avro.AvroStopTimeUpdate.Builder newBuilder(com.fyp.avro.AvroStopTimeUpdate other) {
    if (other == null) {
      return new com.fyp.avro.AvroStopTimeUpdate.Builder();
    } else {
      return new com.fyp.avro.AvroStopTimeUpdate.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroStopTimeUpdate instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroStopTimeUpdate>
    implements org.apache.avro.data.RecordBuilder<AvroStopTimeUpdate> {

    private java.lang.CharSequence stopSequence;
    private java.lang.Integer aDelay;
    private java.lang.Integer dDelay;
    private java.lang.CharSequence stopId;
    private java.lang.CharSequence stopTimeUpdateScheduleRelationship;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fyp.avro.AvroStopTimeUpdate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stopSequence)) {
        this.stopSequence = data().deepCopy(fields()[0].schema(), other.stopSequence);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.aDelay)) {
        this.aDelay = data().deepCopy(fields()[1].schema(), other.aDelay);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dDelay)) {
        this.dDelay = data().deepCopy(fields()[2].schema(), other.dDelay);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.stopId)) {
        this.stopId = data().deepCopy(fields()[3].schema(), other.stopId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.stopTimeUpdateScheduleRelationship)) {
        this.stopTimeUpdateScheduleRelationship = data().deepCopy(fields()[4].schema(), other.stopTimeUpdateScheduleRelationship);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroStopTimeUpdate instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fyp.avro.AvroStopTimeUpdate other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.stopSequence)) {
        this.stopSequence = data().deepCopy(fields()[0].schema(), other.stopSequence);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.aDelay)) {
        this.aDelay = data().deepCopy(fields()[1].schema(), other.aDelay);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dDelay)) {
        this.dDelay = data().deepCopy(fields()[2].schema(), other.dDelay);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.stopId)) {
        this.stopId = data().deepCopy(fields()[3].schema(), other.stopId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.stopTimeUpdateScheduleRelationship)) {
        this.stopTimeUpdateScheduleRelationship = data().deepCopy(fields()[4].schema(), other.stopTimeUpdateScheduleRelationship);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'stopSequence' field.
      * @return The value.
      */
    public java.lang.CharSequence getStopSequence() {
      return stopSequence;
    }


    /**
      * Sets the value of the 'stopSequence' field.
      * @param value The value of 'stopSequence'.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder setStopSequence(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.stopSequence = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stopSequence' field has been set.
      * @return True if the 'stopSequence' field has been set, false otherwise.
      */
    public boolean hasStopSequence() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stopSequence' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder clearStopSequence() {
      stopSequence = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'aDelay' field.
      * @return The value.
      */
    public java.lang.Integer getADelay() {
      return aDelay;
    }


    /**
      * Sets the value of the 'aDelay' field.
      * @param value The value of 'aDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder setADelay(java.lang.Integer value) {
      validate(fields()[1], value);
      this.aDelay = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'aDelay' field has been set.
      * @return True if the 'aDelay' field has been set, false otherwise.
      */
    public boolean hasADelay() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'aDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder clearADelay() {
      aDelay = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dDelay' field.
      * @return The value.
      */
    public java.lang.Integer getDDelay() {
      return dDelay;
    }


    /**
      * Sets the value of the 'dDelay' field.
      * @param value The value of 'dDelay'.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder setDDelay(java.lang.Integer value) {
      validate(fields()[2], value);
      this.dDelay = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dDelay' field has been set.
      * @return True if the 'dDelay' field has been set, false otherwise.
      */
    public boolean hasDDelay() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dDelay' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder clearDDelay() {
      dDelay = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'stopId' field.
      * @return The value.
      */
    public java.lang.CharSequence getStopId() {
      return stopId;
    }


    /**
      * Sets the value of the 'stopId' field.
      * @param value The value of 'stopId'.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder setStopId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.stopId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'stopId' field has been set.
      * @return True if the 'stopId' field has been set, false otherwise.
      */
    public boolean hasStopId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'stopId' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder clearStopId() {
      stopId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'stopTimeUpdateScheduleRelationship' field.
      * @return The value.
      */
    public java.lang.CharSequence getStopTimeUpdateScheduleRelationship() {
      return stopTimeUpdateScheduleRelationship;
    }


    /**
      * Sets the value of the 'stopTimeUpdateScheduleRelationship' field.
      * @param value The value of 'stopTimeUpdateScheduleRelationship'.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder setStopTimeUpdateScheduleRelationship(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.stopTimeUpdateScheduleRelationship = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'stopTimeUpdateScheduleRelationship' field has been set.
      * @return True if the 'stopTimeUpdateScheduleRelationship' field has been set, false otherwise.
      */
    public boolean hasStopTimeUpdateScheduleRelationship() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'stopTimeUpdateScheduleRelationship' field.
      * @return This builder.
      */
    public com.fyp.avro.AvroStopTimeUpdate.Builder clearStopTimeUpdateScheduleRelationship() {
      stopTimeUpdateScheduleRelationship = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroStopTimeUpdate build() {
      try {
        AvroStopTimeUpdate record = new AvroStopTimeUpdate();
        record.stopSequence = fieldSetFlags()[0] ? this.stopSequence : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.aDelay = fieldSetFlags()[1] ? this.aDelay : (java.lang.Integer) defaultValue(fields()[1]);
        record.dDelay = fieldSetFlags()[2] ? this.dDelay : (java.lang.Integer) defaultValue(fields()[2]);
        record.stopId = fieldSetFlags()[3] ? this.stopId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.stopTimeUpdateScheduleRelationship = fieldSetFlags()[4] ? this.stopTimeUpdateScheduleRelationship : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroStopTimeUpdate>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroStopTimeUpdate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroStopTimeUpdate>
    READER$ = (org.apache.avro.io.DatumReader<AvroStopTimeUpdate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.stopSequence);

    if (this.aDelay == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.aDelay);
    }

    if (this.dDelay == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.dDelay);
    }

    out.writeString(this.stopId);

    if (this.stopTimeUpdateScheduleRelationship == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.stopTimeUpdateScheduleRelationship);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.stopSequence = in.readString(this.stopSequence instanceof Utf8 ? (Utf8)this.stopSequence : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.aDelay = null;
      } else {
        this.aDelay = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dDelay = null;
      } else {
        this.dDelay = in.readInt();
      }

      this.stopId = in.readString(this.stopId instanceof Utf8 ? (Utf8)this.stopId : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.stopTimeUpdateScheduleRelationship = null;
      } else {
        this.stopTimeUpdateScheduleRelationship = in.readString(this.stopTimeUpdateScheduleRelationship instanceof Utf8 ? (Utf8)this.stopTimeUpdateScheduleRelationship : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.stopSequence = in.readString(this.stopSequence instanceof Utf8 ? (Utf8)this.stopSequence : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.aDelay = null;
          } else {
            this.aDelay = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dDelay = null;
          } else {
            this.dDelay = in.readInt();
          }
          break;

        case 3:
          this.stopId = in.readString(this.stopId instanceof Utf8 ? (Utf8)this.stopId : null);
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.stopTimeUpdateScheduleRelationship = null;
          } else {
            this.stopTimeUpdateScheduleRelationship = in.readString(this.stopTimeUpdateScheduleRelationship instanceof Utf8 ? (Utf8)this.stopTimeUpdateScheduleRelationship : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










