spring.application.name=spring-app
spring.kafka.bootstrap-servers=localhost:9092

# How to serialise
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

